apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openproject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openproject
    spec:
      containers:
      - name: openproject
        image: openproject/community:8
        ports:
        - name: openproject
          containerPort: 80
