apiVersion: v1
kind: Service
metadata:
  name: openproject
  labels:
    app: openproject
spec:
  type: NodePort
  ports:
  - name: openproject
    targetPort: openproject
  selector:
    app: openproject
