apiVersion: v1
kind: Service
metadata:
  name: iproject
  labels:
    app: iproject
spec:
  type: NodePort
  ports:
  - name: iproject
    targetPort: iproject
    port: {{ .Values.service.port }}
  selector:
    app: iproject
